### ISSUE TITLE
Broken in Sierra

### ISSUE THREAD

**Issue by simonhowes** [jrk/afsctool#1]
Appears not to compress under Sierra.

**Comment by jrk** [comment]
I didn’t make this; it’s based on some GPL code found on a pastebin somewhere ~7 years ago (see the links in the README), and I just packaged it somewhere more visible, with links to the collection of related discussions and a proper Makefile.
I may take a look if I get a chance, but fixes are welcome.
What behavior do you see?

**Comment by jrk** [comment]
Should be fixed by the commit from @alistairmcmillan.
